envinfo.js

Try to fetch xcodebuild path only when `process.platform` returns `darwin` value
Fix for https://github.com/tabrindle/envinfo/issues/3

Try to fetch xcodebuild path only on 'darwin' devices

---

package.json
src/envinfo.js
src/formatters.js
src/utils.js
yarn.lock

The custom formatters were causing me pain. 
Problem 1 is that they were custom. I was traversing the data structure as if it couldn't change. Guess what? It did. 🤦‍♂️ 
Problem 2 is that they weren't really extensible. The refactor is much more functional and creates a framework for creating custom reformatters, and will allow for future formats to be more easily added. Now there is a clean function that can remove `N/A` or anything else we want, easily changed by options. There's also a custom formatter for terminal formatting (underline, bold etc)
Sorta Problem 3 the custom table I was creating was my own crappy invention. It wasn't too far from how YAML looks, so I made YAML the default. Interoperability between JSON and yaml make conversion easier.

refactor: use yaml as default table, modularize custom logic in formatters

---

src/envinfo.js
src/helpers.js
src/map.js

`envinfo --languages`
- Bash: 4.4.12
- Go: 1.9.3
- Elixir: 1.6.2
- PHP: 7.1.7
- Python: 2.7.10
- Ruby: 2.3.3p222

feat: add elixir to Languages

---

src/helpers.js
src/utils.js

If the user doesn't have `subl` set up like I did :noob: envinfo would not register it.

Fix sublime version without subl

---

__tests__/envinfo.test.js
src/cli.js
src/formatters.js

Add a custom title option.
`envinfo --title 'env report 🎉'`
```
env report 🎉:
System:
OS: macOS High Sierra 10.13
CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Memory: 167.72 MB / 16.00 GB
```

feat: add title option for reports

---

README.md

exp has been deprecated in favor of expo-cli.

Update exp to expo-cli in README.md

---

.circleci/config.yml
src/helpers.js

Also add react native test image, output looks like this:
```
System:
OS: Linux 4.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
Memory: 1.10 GB / 68.70 GB
Container: Yes
Shell: 4.4.12 - /bin/bash
Binaries:
Node: 10.14.2 - /usr/bin/node
Yarn: 1.12.3 - /usr/bin/yarn
npm: 6.4.1 - /usr/bin/npm
Utilities:
Make: 4.1 - /usr/bin/make
GCC: 6.3.0 - /usr/bin/gcc
Git: 2.11.0 - /usr/bin/git
SDKs:
Android SDK:
API Levels: 28
Build Tools: 28.0.2
System Images: android-19 | Google APIs ARM EABI v7a
Android NDK: 17.2.4988734
Languages:
Bash: 4.4.12 - /bin/bash
Java: 1.8.0 - /usr/bin/javac
Perl: 5.24.1 - /usr/bin/perl
Python: 2.7.13 - /usr/bin/python
Databases:
SQLite: 3.22.0 - /opt/android/platform-tools/sqlite3
```

fix ndk bug and add support for ENV ANDROID_NDK_HOME. Fixes #75.

---

__tests__/utils.test.js
src/helpers.js

New output:
```yaml
System:
OS: macOS 10.14.2
CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Memory: 589.07 MB / 16.00 GB
Shell: 5.3 - /bin/zsh
Binaries:
Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
Yarn: 1.12.3 - ~/.yarn/bin/yarn
npm: 6.4.1 - ~/.nvm/versions/node/v8.14.0/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Utilities:
Make: 3.81 - /usr/bin/make
GCC: 10.14. - /usr/bin/gcc
Git: 2.20.0 - /usr/local/bin/git
Servers:
Apache: 2.4.34 - /usr/sbin/apachectl
Virtualization:
Docker: 18.09.0 - /usr/local/bin/docker
VirtualBox: 5.2.20 - /usr/local/bin/vboxmanage
SDKs:
iOS SDK:
Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
Android SDK:
API Levels: 28
Build Tools: 28.0.3
System Images: android-28 | Google Play Intel x86 Atom
IDEs:
Android Studio: 3.2 …
```

fix: was checking rustup instead of rustc :facepalm:

---

src/presets.js

Will output like this:
```
System:
OS: macOS 10.14.2
CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Memory: 324.38 MB / 16.00 GB
Binaries:
Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
Yarn: 1.12.3 - ~/.yarn/bin/yarn
npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
npmPackages:
@babel/core: ^7.2.2 => 7.2.2 
@babel/plugin-proposal-optional-chaining: ^7.2.0 => 7.2.0 
@babel/polyfill: ^7.2.5 => 7.2.5 
@babel/preset-env: ^7.3.1 => 7.3.1 
babel-core: 7.0.0-bridge.0 => 7.0.0-bridge.0 
babel-eslint: ^10.0.1 => 10.0.1 
babel-jest: 23.6.0 => 23.6.0 
babel-loader: ^8.0.5 => 8.0.5 
nyc: ^13.3.0 => 13.3.0 
```
Until we can add regex to npmPackages args, one big glob will have to do. No showNotFound option though :-/

fix: use big glob for nyc preset

---

__tests__/utils.test.js
src/helpers/utilities.js
src/presets.js

Fix https://github.com/tabrindle/envinfo/issues/86.
```console
System:
OS: Linux 4.15 Ubuntu 19.04 (Disco Dingo)
CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
Memory: 31.36 GB / 68.69 GB
Container: Yes
Shell: 5.0.3 - /bin/bash
Binaries:
Node: 12.4.0 - /usr/local/bin/node
Yarn: 1.16.0 - /usr/local/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Utilities:
CMake: 3.10.2 - /usr/local/bin/cmake
Make: 4.2.1 - /usr/bin/make
GCC: 8.3.0 - /usr/bin/gcc
Git: 2.20.1 - /usr/bin/git
Clang: 8.0.0-3 - /usr/bin/clang
```

add clang support.

---

src/presets.js

This will let the apollo preset capture info about the upcoming `@apollo/react-components`, `@apollo/react-hoc`, and `@apollo/react-hooks` packages. 😄

Add @apollo namespace to preset

---

src/helpers/sdks.js

getAndroidSDKInfo was not working on Windows because $ANDROID_HOME is a Mac-specific way to use environment variables. This uses the variable from process.env instead.

fix: Android SDK info not working on Windows

---

src/helpers/system.js

On Arch Linux there is no versionInfo available. This PR solves printing 'undefined' in OS info.
Related to  #112

prevent printing versionInfo if its not available

---

src/cli.js
src/helpers/index.js
src/helpers/monorepos.js
src/presets.js

Implement `monorepos` support for #126. The version of `Yarn Workspaces` is the one of `Yarn`, and `Lerna` is straightforward.
Example output on babel repository.
```sh
$  envinfo --monorepos --showNotFound
Monorepos:
Yarn Workspaces: Not Found
Lerna: 3.16.4
```

implement monorepos

---

src/presets.js

This PR introduces `babel` preset and we plan to offer `npx envinfo --preset babel` in our issue template.
Example output:
```
System:
OS: macOS 10.15
Binaries:
Node: 12.11.1 - /usr/local/bin/node
Yarn: 1.19.1 - /usr/local/bin/yarn
npm: 6.11.3 - /usr/local/bin/npm
npmPackages:
@babel/core: ^7.6.0 => 7.6.0 
@babel/plugin-proposal-class-properties: ^7.5.5 => 7.5.5 
@babel/plugin-proposal-numeric-separator: ^7.2.0 => 7.2.0 
@babel/plugin-proposal-private-methods: ^7.6.0 => 7.6.0 
@babel/preset-env: ^7.6.0 => 7.6.0 
eslint: ^6.5.1 => 6.5.1 
```

feat: add babel preset

---

src/helpers/languages.js

Fix #136
on my Windows 10:
```console
Languages:
Go: 1.13.4 - C:\Go\bin\go.EXE
Java: 1.8.0_201 - C:\Program Files\Java\jdk1.8.0_201\bin\javac.EXE
Perl: 5.26.2 - C:\Program Files\Git\usr\bin\perl.EXE
Python: 3.8.0 - C:\Python38\python.EXE
R: 3.6.0 - C:\Program Files\R\R-3.6.0\bin\x64\R.EXE
Rust: 1.39.0 - C:\ProgramData\chocolatey\bin\rustc.EXE
```

fix rust version info

---

src/helpers/sdks.js
src/utils.js

In this PR we removed i) `fs.stat` call before` fs.readFile` and ii) `fs.existsSync` call before `fs.readFileSync`.
The first call pattern would introduce race condition because `fs.stat` is asynchronous, which means other process could change the file's state between `fs.stat` and `fs.readFile`.
The second call pattern introduces duplicate IO operations. `fs.readFileSync` will throw `ENOENT` when file does not exists and later this error will be caught and converted to `null`. Therefore it is unnecessary to call `fileExists` before `readFile`.

remove unnecessary fs calls

---

README.md

Looking through the docs, it wasn't clear that `envinfo.run` returned a promise.  This PR attempts to clarify that

docs: update programmatic example

---

src/helpers/browsers.js
src/utils.js

adding support to detect microsoft edge on macos.  tested on macos `10.15.3`.
`node src/cli.js --browsers` gives me the following output:
```
Browsers:
Chrome: 80.0.3987.122
Chrome Canary: 82.0.4069.0
Edge: 80.0.361.57
Firefox: 72.0.2
Safari: 13.0.5
```

add edge support on macos

---

__tests__/utils.test.js
src/helpers/system.js

This PR fixes issue https://github.com/tabrindle/envinfo/issues/81.  The work was mostly done here but got reverted at some point.  I also added a test for `ash`.
I tested this in an alpine linux docker container locally as well.

fixing hang in alpine linux and adding test

---

src/packages.js

Fix: https://github.com/tabrindle/envinfo/issues/143
[npm-folders: Node Modules](https://docs.npmjs.com/files/folders.html#node-modules)
> Global installs on Unix systems go to {prefix}/lib/node_modules. Global installs on Windows go to {prefix}/node_modules (that is, no lib folder.)

fix --npmGlobalPackages on windows

---

yarn.lock

I'm not sure why but on two of my PRs https://github.com/tabrindle/envinfo/pull/161 & https://github.com/tabrindle/envinfo/pull/152, the travis build fails on every node version with this error:
```
6.10s$ yarn --frozen-lockfile
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "eval yarn --frozen-lockfile " failed. Retrying, 2 of 3.
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this …
```

update yarn lockfile

---

.travis.yml

Here's a passing build. Yarn lets us [ignore the engines errors](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-ignore-engines) which I think is the best route to take here given the build is still successful.
Fixes #172

build: ignore engines errors

---

src/envinfo.js

`utils.omit` will error if `presets[options.preset]` is undefined

fix(cli): return early if no preset is found

---

src/helpers/sdks.js

The proper `sdkmanager` may not be located at `${ANDROID_HOME}/tools/bin/sdkmanager`, so try all possible path one by one. Does this strategy fit the requirement of #168 ?

Does not recognize Android SDK on Mac (#168)

---

src/presets.js

It was not working before, oriented at the Babel examples but maybe I don't understand glob.
See here for before and after: https://github.com/microsoft/playwright/pull/2237#issuecomment-682379103

fix(presets): find Playwright NPM packages

---

src/helpers/system.js

closes https://github.com/tabrindle/envinfo/issues/190

fix: default to empty string if distro is null

---

README.md
__tests__/__snapshots__/envinfo.test.js.snap
src/helpers/binaries.js
src/presets.js

- add [bun](https://github.com/oven-sh/bun) to listed binaries

feat: add bun in binaries

---

src/helpers/system.js

fixes #209
Currently, Windows 11 systems are recognized as Windows 10, this PR will fix that.

fix: Windows 11 information

---

src/presets.js

Added next and rollup to `npmPackages` as next bundled `@babel/core` and `rollup` can work with `@babel/core` via `@rollup-plugin/babel`.

feat: Update Babel preset

---

README.md

I have included [FakerJS](https://fakerjs.dev/) in the list of libraries that utilize `envinfo` in their ISSUE_TEMPLATES. [Our Bug Report Template recommends using your library](https://github.com/faker-js/faker/blob/3f70b0ac31520885c39fd79d18750e2701a22b28/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L69).
Should you decide against adding us to the list, please feel free to close this PR. I believe that having community cross-references could be mutually beneficial for both libraries in terms of visibility.

docs: add FakerJS to ISSUE_TEMPLATE users
