tabrindle/envinfo

- package.json
- src/envinfo.js
> add flag to disable xcode and android studio detection

- README.md
This PR fixes the formatting which looks weird on npmjs.
Someone could end up running a wrong command.
> FIX: Better Formatting

- src/helpers.js
- src/map.js
Hi @tabrindle,
I noticed there are no versions for Google Chrome and Firefox on Linux, here is small PR to get them.
Before:
After:
> Show Google Chrome and Firefox versions on Linux

- src/envinfo.js
- src/formatters.js
- src/helpers.js
- src/map.js
Closes #15 
Keep in mind I have MANY Android SDKs installed
> android sdks mapped

- src/helpers.js
- src/presets.js
Git, Make, CMake, GCC, Nano, Emacs, Vim, Rust, Scala, Java, Apache, Nginx
> feat: add a crap ton more features

- README.md
- src/helpers.js
- src/presets.js
- src/utils.js
Added PhpStorm, IntelliJ and WebStorm
> Feature/add more IDEs support

- .circleci/config.yml
You may need to squash the commit.
https://circleci.com/gh/gengjiawen/envinfo/tree/feature%2Flinux_test
Related issue: https://github.com/tabrindle/envinfo/issues/65.
> add linux test (ubuntu, debian, centos).Fixes #65

- README.md
- __tests__/utils.test.js
- src/envinfo.js
- src/helpers.js
> fix: java version to include after _

- src/helpers.js
```
➜  envinfo git:(bugfix/ash) ✗ docker run -v $PWD:/src -w /src -u node -it --rm node:alpine sh
/src $ node src/cli.js
System:
OS: Linux 4.9 Alpine Linux
CPU: (4) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Memory: 287.52 MB / 1.95 GB
Container: Yes
Shell: 1.28.4 - /bin/ash
Binaries:
Node: 11.6.0 - /usr/local/bin/node
Yarn: 1.12.3 - /usr/local/bin/yarn
npm: 6.5.0-next.0 - /usr/local/bin/npm
```
this closes #81
> fix: alpine crash on shell detection

- src/presets.js
Hi! @istanbuljs member here, just wanting to improve our issue template. Thank you for this amazing package! Let me know if I need to fix anything or if you think I missed something :) 
cc @bcoe @coreyfarrell
> add nyc preset

- __tests__/__snapshots__/envinfo.test.js.snap
- __tests__/envinfo.test.js
Hey again - just wanted to try to help out and start with something easy for me - I think this change makes the tests a bit easier to maintain and read :)
> tests: simplify envinfo tests with snapshots

- appveyor.yml
- src/helpers.js
- src/utils.js
* The version info is in the stderr stream, I guess this is why `2>&1` is used.
> support java version on windows

- __tests__/__snapshots__/envinfo.test.js.snap
- __tests__/envinfo.test.js
- src/envinfo.js
> fix: disable console formatter option when stdout is not terminal

- src/helpers/ides.js
> fix bug on termux

- src/helpers/browsers.js
- src/presets.js
- src/utils.js
Add another borwser in the list: Brave
> Add Brave in the list of browsers

- src/helpers/utilities.js
> make cmake works on windows

- src/helpers/system.js
New output
```console
System:
OS: Windows 10 10.0.18363
CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Memory: 5.72 GB / 15.89 GB
```
> add windows version in OS

- src/helpers/utilities.js
on My windows
```console
Utilities:
CMake: 3.15.4 - c:\Program Files\CMake\bin\cmake.EXE
Git: 2.24.0. - C:\Program Files\Git\cmd\git.EXE
```
> add git support in windows

- src/helpers/languages.js
- src/presets.js
adds Erlang support. I tested this on macos and linux.  
issue https://github.com/tabrindle/envinfo/issues/106
> adding support for erlang

- .circleci/config.yml
> add alpine to CI

- src/utils.js
Users on windows will probably appreciate this
https://nodejs.org/api/os.html#os_os_homedir
> replace process.env.HOME with os.homedir()

- __tests__/__snapshots__/scopedPackages.test.js.snap
- __tests__/packages/test-duplicates/node_modules/@scoped-name/test/package.json
- __tests__/packages/test-duplicates/package.json
- __tests__/scopedPackages.test.js
- src/packages.js
closes: https://github.com/tabrindle/envinfo/issues/160
I don't have a windows machine to test on but the tests should on appveyor
> Parse package path windows support

- src/presets.js
Adds support for Playwright, see this issue for linking reference: https://github.com/microsoft/playwright/issues/2027
Thanks!
> feat: added support for Playwright

- commitlint.config.js
- package.json
- yarn.lock
This is the first step in making a more automated release process. Make commit messages follow conventional commits, so we can automagically make changelogs and determine the next semver.
> feat: add commitlint and husky

- src/helpers/ides.js
https://www.jetbrains.com/toolbox-app/
> feat: search in Jetbrains Toolbox path for Android Studio

- __tests__/utils.test.js
- src/helpers/system.js
Fix #97 
I have checked debian, ubuntu, centOS, looks like working on all three :)
> add GLibc support

- src/helpers/utilities.js
Fix https://github.com/tabrindle/envinfo/issues/197
> fix: improve clang version detect

- src/helpers/browsers.js
- src/presets.js
This PR includes:
* Brave: take into account of a new command line for Linux (`brave-browser`)
* Chromium: add this brower
> feat: update brave command line and add chromium

- src/helpers/ides.js
fix #222
macOS not supported this anymore.
> fix: stuck on macOS

- .gitattributes
- src/helpers/browsers.js
- src/utils.js
I added support for finding the Firefox web browser on Windows.
However, I couldn't test or debug my changes as there were too many conventions I had to follow to get this running on my Windows machine.
Before merging, please test my changes. Thank you.
/fixes: #221
> feat: support for finding firefox web browser on windows added

- src/helpers/virtualization.js
Adds [podman](https://podman.io/) to virtualization data
> feat: add podman to virtualization

- src/presets.js
Drive-by:
- add VSCode version check for Extension troubleshooting
- Add CPU info for parallel workers troubleshooting
> fix: add @playwright/ to playwright preset

- src/helpers/utilities.js
- src/presets.js
fix https://github.com/tabrindle/envinfo/issues/203
> feat: add openssl support

- src/helpers/utilities.js
- src/presets.js
fix: https://github.com/tabrindle/envinfo/issues/230
> feat: add ccache

- src/helpers/browsers.js
fix: https://github.com/tabrindle/envinfo/issues/268
> fix: windows chrome and firefox detection
